export const moodOptions = [
    {
        id: 'happy',
        mood_id: 1,
        emoji: '😊',
        label: 'Happy',
        backgroundColor: '#FFF4CC',
        textColor: '#8A6D00',
        meaning: 'Warm yellow, positive mood',
    },
    {
        id: 'calm',
        mood_id: 2,
        emoji: '😌',
        label: 'Calm',
        backgroundColor: '#E6F4F1',
        textColor: '#2F6F6A',
        meaning: 'Relaxed, peaceful',
    },
    {
        id: 'sad',
        mood_id: 3,
        emoji: '💙',
        label: 'Sad',
        backgroundColor: '#E8F0FE',
        textColor: '#2C4A8A',
        meaning: 'Soft blue for sadness',
    },
    {
        id: 'angry',
        mood_id: 4,
        emoji: '😡',
        label: 'Angry',
        backgroundColor: '#FFE5E5',
        textColor: '#8B2E2E',
        meaning: 'Light red tone',
    },
    {
        id: 'anxious',
        mood_id: 5,
        emoji: '😰',
        label: 'Anxious',
        backgroundColor: '#F3E8FF',
        textColor: '#5E3A87',
        meaning: 'Purple tone, worried feeling',
    },
    {
        id: 'reflective',
        mood_id: 6,
        emoji: '🤔',
        label: 'Reflective',
        backgroundColor: '#ECECEC',
        textColor: '#444444',
        meaning: 'Neutral thinking mood',
    },
    {
        id: 'grateful',
        mood_id: 7,
        emoji: '🥰',
        label: 'Grateful',
        backgroundColor: '#E8F8F0',
        textColor: '#2D6A4F',
        meaning: 'Green gratitude',
    },
    {
        id: 'tired',
        mood_id: 8,
        emoji: '🌙',
        label: 'Tired',
        backgroundColor: '#E9E6F8',
        textColor: '#4B4B8F',
        meaning: 'Soft lavender',
    },
];
